# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unsuperviseUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UnsuperviseDialog(object):
    def setupUi(self, UnsuperviseDialog):
        UnsuperviseDialog.setObjectName("UnsuperviseDialog")
        UnsuperviseDialog.resize(540, 240)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/非监督分类.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UnsuperviseDialog.setWindowIcon(icon)
        UnsuperviseDialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtReclassPath = QtWidgets.QTextEdit(UnsuperviseDialog)
        self.txtReclassPath.setGeometry(QtCore.QRect(100, 20, 291, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.txtReclassPath.setFont(font)
        self.txtReclassPath.setObjectName("txtReclassPath")
        self.label = QtWidgets.QLabel(UnsuperviseDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ok = QtWidgets.QPushButton(UnsuperviseDialog)
        self.ok.setGeometry(QtCore.QRect(330, 190, 81, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.ok.setFont(font)
        self.ok.setObjectName("ok")
        self.label_2 = QtWidgets.QLabel(UnsuperviseDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 61, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtOutputPath = QtWidgets.QTextEdit(UnsuperviseDialog)
        self.txtOutputPath.setGeometry(QtCore.QRect(100, 90, 291, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.txtOutputPath.setFont(font)
        self.txtOutputPath.setObjectName("txtOutputPath")
        self.quit = QtWidgets.QPushButton(UnsuperviseDialog)
        self.quit.setGeometry(QtCore.QRect(430, 190, 81, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.quit.setFont(font)
        self.quit.setObjectName("quit")
        self.chooseReclass = QtWidgets.QPushButton(UnsuperviseDialog)
        self.chooseReclass.setGeometry(QtCore.QRect(410, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.chooseReclass.setFont(font)
        self.chooseReclass.setObjectName("chooseReclass")
        self.chooseOutput = QtWidgets.QPushButton(UnsuperviseDialog)
        self.chooseOutput.setGeometry(QtCore.QRect(410, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.chooseOutput.setFont(font)
        self.chooseOutput.setObjectName("chooseOutput")
        self.label_3 = QtWidgets.QLabel(UnsuperviseDialog)
        self.label_3.setGeometry(QtCore.QRect(100, 60, 401, 16))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(UnsuperviseDialog)
        self.label_4.setGeometry(QtCore.QRect(100, 130, 431, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(UnsuperviseDialog)
        QtCore.QMetaObject.connectSlotsByName(UnsuperviseDialog)

    def retranslateUi(self, UnsuperviseDialog):
        _translate = QtCore.QCoreApplication.translate
        UnsuperviseDialog.setWindowTitle(_translate("UnsuperviseDialog", "非监督分类"))
        self.label.setText(_translate("UnsuperviseDialog", "分类文件："))
        self.ok.setText(_translate("UnsuperviseDialog", "分  类"))
        self.label_2.setText(_translate("UnsuperviseDialog", "输出路径："))
        self.quit.setText(_translate("UnsuperviseDialog", "关  闭"))
        self.chooseReclass.setText(_translate("UnsuperviseDialog", "选择分类文件"))
        self.chooseOutput.setText(_translate("UnsuperviseDialog", "选择输出目录"))
        self.label_3.setText(_translate("UnsuperviseDialog", "注意：请选择要进行非监督分类的遥感影像，支持.tif格式。"))
        self.label_4.setText(_translate("UnsuperviseDialog", "<html><head/><body><p>注意：请选择非监督分类后影像的输出目录，文件会以UnsupervisedResult.tif</p><p>后缀命名。</p></body></html>"))
import ucRc_rc
